--- 
- hosts: 172.31.31.34
  become: yes
  tasks:
  - include_tasks: installjava.yml 
     
- hosts: 172.31.31.34
  become: yes
  tasks:
  - include_tasks: myfile.yml

- hosts: 172.31.31.34
  become: yes
  tasks: 
  - include_tasks: nginx.yml

- hosts: 172.31.31.34
  become: yes
  tasks: 
  - include_tasks: myfolder.yml
 
  - name: copy file into folder
    copy: 
     src: staticfile
     dest: /home/admin/myfolder/staticfile

  - name: cr folder
    file:
     path: /home/admin/pradeep
     state: directory
  
  - name: index pages
    template: 
      src: index.j2
      dest: /var/www/html/index.nginx-debian.html



     
   
