--- 
- hosts: 172.31.31.34
  become: yes
  tasks:
  - include_tasks: installjava.yml 
     
- hosts: 172.31.31.34
  become: yes
  tasks:
  - include_tasks: myfile.yml

- hosts: 172.31.31.34
  become: yes
  tasks: 
  - include_tasks: nginx.yml

- hosts: 172.31.31.34
  become: yes
  tasks: 
  - include_tasks: myfolder.yml



     
   
