--- 
- name: create group 
  group:
   name: tomcat
   state: present

- name: create user and add user to above group 
  user:
    name: tomcat 
    shell: /bin/false
    home: /opt/tomcat
    group: tomcat
    state: present 